version: "3"

services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TZ: "America/Chicago"
      VERSION: "1.16.5"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - dwyce:/data


volumes:
    dwyce:
      driver: azure_file
      driver_opts:
        share_name: minecraft-dwyce-volume
        storage_account_name: minecraftdwycestorage