version: "3.7"

services:
  mc:
    image: itzg/minecraft-server
    domainname: dwyce-minecraft
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - mcvolume:/data


volumes:
    mcvolume:
      driver: azure_file
      driver_opts:
        share_name: minecraft-dwyce-volume
        storage_account_name: minecraftdwycestorage